## Packages

In [59]:
import numpy as np

## Matrix Addition

### Concept

Let's assume there is $2\times 3$ 2-dimensional matrices $\mathbf{A}, \mathbf{B}$ as

$$\mathbf{A}=\left(\begin{matrix}0&5&-2\\-1&5&3\end{matrix}\right),\ \mathbf{B}=\left(\begin{matrix}5&-3&9\\-2&1&-4\end{matrix}\right) \tag{1}$$

Matrix (1) can be generalized as

$$\mathbf{A}=\left(\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\\end{matrix}\right),\ \mathbf{B}=\left(\begin{matrix}b_{11}&b_{12}&b_{13}\\b_{21}&b_{22}&b_{23}\\\end{matrix}\right)\tag{2}$$

Generalized addition of matrices $\mathbf{A}, \mathbf{B}$ can be denoted by

$$\mathbf{A}+\mathbf{B}=\left(\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\\end{matrix}\right)+\left(\begin{matrix}b_{11}&b_{12}&b_{13}\\b_{21}&b_{22}&b_{23}\\\end{matrix}\right)=\left(\begin{matrix}a_{11}+b_{11}&a_{12}+b_{12}&a_{13}+b_{13}\\a_{21}+b_{21}&a_{22}+b_{22}&a_{23}+b_{23}\\\end{matrix}\right)\tag{3}$$

With (1) and (3), matrix addition of $\mathbf{A}$ and $\mathbf{B}$ can be calculated by

$$\mathbf{A}+\mathbf{B}=\left(\begin{matrix}0&5&-2\\-1&5&3\end{matrix}\right)+\left(\begin{matrix}5&-3&9\\-2&1&-4\end{matrix}\right)=\left(\begin{matrix}5&2&7\\-3&6&-1\end{matrix}\right) \tag{4}$$

### Naive Method

Let's assume there is $2\times 3$ 2-dimensional matrices $\mathbf{A}, \mathbf{B}$ as (1)

In [60]:
a = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

b = np.array([
    [5, -3, 9],
    [-2, 1, -4]
])

We can make algorithm for addition on matrices $\mathbf{A}$ and $\mathbf{B}$ using nested for loop as

<hr style="width: 100%; margin-left: 0; margin-bottom: 0px; border: 0.5px solid black;">
<strong>Algorithm</strong> naive_add(a, b)
<hr style="width: 100%; margin-left: 0; margin-top: 0px; margin-bottom: 0px; border: 0.5px solid black;">
<strong>Input</strong> $m\times n$ 2-dimensional matrices $\mathbf{A}$ and $\mathbf{B}$<br>
&emsp; <strong>Let</strong> $\mathbf{C}$ ← copy of $\mathbf{A}$<br>
&emsp; <strong>for</strong> $i=0$ <strong>to</strong> $m-1$ <strong>do</strong><br>
&emsp;&emsp; <strong>for</strong> $j=0$ <strong>to</strong> $n-1$ <strong>do</strong><br>
&emsp;&emsp;&emsp; $\mathbf{C}[i][j]=\mathbf{C}[i][j]+\mathbf{B}[i][j]$ <br>  
<strong>Output</strong> $m\times n$ 2-dimensional matrix $\mathbf{C}$, sum of $\mathbf{A}$ and $\mathbf{B}$
<hr style="width: 100%; margin-left: 0; margin-top: 0px; border: 0.5px solid black;">

With algorithm, we can apply matirx addition on python as

In [61]:
def naive_add(a, b):
    assert len(a.shape) == 2
    assert a.shape == b.shape
    c = a.copy()
    for i in range(c.shape[0]):
        for j in range(c.shape[1]):
            c[i, j] += b[i, j]
    return c
naive_add(a, b)

array([[ 5,  2,  7],
       [-3,  6, -1]])

### Vectorized Method

In [62]:
a = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

b = np.array([
    [5, -3, 9],
    [-2, 1, -4]
])

In [63]:
y = a + b
y

array([[ 5,  2,  7],
       [-3,  6, -1]])

## Relu

### Concept

![image](img/graph-relu.png)

$$f(y)=max(0, x) \tag{5}$$

(5) can be denoted by

$$f(y)=\begin{cases}0,\ x< 0\\x,\ x\geq 0\end{cases} \tag{6}$$

Let's assume there is $2\times 3$ 2-dimensional matrix $\mathbf{X}$ as

$$\mathbf{X}=\left(\begin{matrix}0&5&-2\\-1&5&3\\\end{matrix}\right)\tag{7}$$

Matrix (7) can be generalized as

$$\mathbf{X}=\left(\begin{matrix}x_{11}&x_{12}&x_{13}\\x_{21}&x_{22}&x_{23}\\\end{matrix}\right)\tag{8}$$

Based on (8), if we apply (6) on (7) element-wise,

<div align="center">

|$x$|Case|$f(x)$|$y$|
|:-:|:-:|:-:|:-:|
|$x_{11}=0$|$0\geq 0$|$y=x$|$x_{11}=0$  |
|$x_{12}=5$|$5\geq 0$|$y=x$|$x_{12}=5$ |
|$x_{13}=-2$|$-2<0$|$y=0$|$x_{13}=0$ |
|$x_{21}=-1$|$-1<0$|$y=0$|$x_{21}=0$ |
|$x_{22}=5$|$5\geq 0$|$y=x$|$x_{22}=5$ |
|$x_{23}=3$|$3\geq 0$|$y=x$|$x_{23}=3$ |

</div>

Therefore, we can get matrix applied ReLU as

$$\mathbf{Y}=\left(\begin{matrix}0&5&0\\0&5&3\\\end{matrix}\right) \tag{8}$$

### Naive Method

Let's assume there is $2\times 3$ 2-dimensional matrix $\mathbf{X}$ as (7)

In [64]:
x = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

We can make algorithm for ReLU on matrix $\mathbf{X}$ using nested for loop as

<hr style="width: 100%; margin-left: 0; margin-bottom: 0px; border: 0.5px solid black;">
<strong>Algorithm</strong> naive_relu(x)
<hr style="width: 100%; margin-left: 0; margin-top: 0px; margin-bottom: 0px; border: 0.5px solid black;">
<strong>Input</strong> $m\times n$ 2-dimensional matrix $\mathbf{X}$<br>
&emsp; <strong>Let</strong> $\mathbf{Y}$ ← copy of $\mathbf{X}$<br>
&emsp; <strong>for</strong> $i=0$ <strong>to</strong> $m-1$ <strong>do</strong><br>
&emsp;&emsp; <strong>for</strong> $j=0$ <strong>to</strong> $n-1$ <strong>do</strong><br>
&emsp;&emsp;&emsp; <strong>if</strong> $\mathbf{Y}[i][j]<0$ <strong>then</strong><br> 
&emsp;&emsp;&emsp;&emsp; $\mathbf{Y}[i][j]$ ← $0$<br>
<strong>Output</strong> $m\times n$ 2-dimensional matrix $\mathbf{Y}$ with ReLU applied
<hr style="width: 100%; margin-left: 0; margin-top: 0px; border: 0.5px solid black;">

With algorithm, we can apply ReLU on python as

In [65]:
def naive_relu(x):
    assert len(x.shape) == 2
    y = x.copy()
    for i in range(y.shape[0]):
        for j in range(y.shape[1]):
            y[i, j] = max(y[i, j], 0)
    return y
naive_relu(x)

array([[0, 5, 0],
       [0, 5, 3]])

### Vectorized Method

Like previous method, assume $2\times 3$ 2-dimensional matrix $\mathbf{X}$ as

In [66]:
x = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

In [67]:
y = np.maximum(x, 0.)
y

array([[0., 5., 0.],
       [0., 5., 3.]])

## Comparing Execution Time: Naive vs. Vectorized Methods

### Matrix Addition

### ReLU

In [68]:
import time
x = np.random.uniform(-10, 10, size=(20, 100))

t0 = time.time()
for _ in range(1000):
    y = naive_relu(x)
print("Naive method took: {0:.2f} s".format(time.time() - t0))

t0 = time.time()
for _ in range(1000):
    y = np.maximum(x, 0.)
print("Vectorized method took: {0:.2f} s".format(time.time() - t0))

Naive method took: 0.85 s
Vectorized method took: 0.00 s


When we see the code above, we can see that naive method need more time for applying ReLU function compared to vectorized method.