## Packages

In [49]:
import numpy as np

## Matrix Addition

### Concept

Let's assume there is $2\times 3$ 2-dimensional matrix $\mathbf{A}, \mathbf{B}$ as

$$\mathbf{A}=\left(\begin{matrix}0&5&-2\\-1&5&3\end{matrix}\right),\ \mathbf{B}=\left(\begin{matrix}5&-3&9\\-2&1&-4\end{matrix}\right) \tag{1}$$

We can get summation of matrix $\mathbf{A}, \mathbf{B}$ as

$$\mathbf{A}+\mathbf{B}=\left(\begin{matrix}0&5&-2\\-1&5&3\end{matrix}\right)+\left(\begin{matrix}5&-3&9\\-2&1&-4\end{matrix}\right)=\left(\begin{matrix}5&2&7\\-3&6&-1\end{matrix}\right) \tag{2}$$

### Naive Method

In [50]:
a = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

b = np.array([
    [5, -3, 9],
    [-2, 1, -4]
])

In [51]:
def naive_add(a, b):
    assert len(a.shape) == 2
    assert a.shape == b.shape
    a = a.copy()
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            a[i, j] += b[i, j]
    return a
naive_add(a, b)

array([[ 5,  2,  7],
       [-3,  6, -1]])

### Vectorized Method

In [52]:
a = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

b = np.array([
    [5, -3, 9],
    [-2, 1, -4]
])

In [53]:
y = a + b
y

array([[ 5,  2,  7],
       [-3,  6, -1]])

## Relu

### Concept

![image](img/graph-relu.png)

$$y=max(0, x) \tag{1}$$

Equation (1) can be denoted by (2)

$$y=\begin{cases}0,\ x> 0\\x,\ x\leq 0\end{cases} \tag{2}$$

### Naive Method

In [54]:
x = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

Let's assume there is $2\times 3$ 2-dimensional matrix $\mathbf{X}$ as (3)

$$\mathbf{X}=\left(\begin{matrix}0&5&-2\\-1&5&3\\\end{matrix}\right)\tag{3}$$

In [55]:
def naive_relu(x):
    assert len(x.shape) == 2
    y = x.copy()
    for i in range(y.shape[0]):
        for j in range(y.shape[1]):
            y[i, j] = max(y[i, j], 0)
    return y
naive_relu(x)

array([[0, 5, 0],
       [0, 5, 3]])


<table style="border-collapse: collapse; width: 100%;">
<td style="border-top: none; border-bottom: 1px solid black; border-left: none; border-right: none; padding: 8px;">
  <tr>
    <td style="border-top: none; border-bottom: 1px solid black; border-left: none; border-right: none; padding: 8px;">
      <strong>Algorithm</strong> naive_relu(x)
    </td>
  </tr>
  <tr>
    <td style="border-top: none; border-bottom: 1px solid black; border-left: none; border-right: none; padding: 8px;">
      <strong>Input</strong> $m\times n$ 2-dimensional matrix $\mathbf{X}$<br>
      &emsp; <strong>Let</strong> $\mathbf{Y}$ ← copy of $\mathbf{X}$<br>
      &emsp; <strong>for</strong> $i=0$ <strong>to</strong> $m-1$ <strong>do</strong><br>
      &emsp;&emsp; <strong>for</strong> $j=0$ <strong>to</strong> $n-1$ <strong>do</strong><br>
      &emsp;&emsp;&emsp; <strong>if</strong> $\mathbf{Y}[i][j]<0$ <strong>then</strong><br> 
      &emsp;&emsp;&emsp;&emsp; $\mathbf{Y}[i][j]$ ← $0$<br>
      <strong>Output</strong> $m\times n$ 2-dimensional matrix $\mathbf{Y}$ with ReLU applied
    </td>
  </tr>
</table>

If we apply ReLU function to matrix $\mathbf{X}$ on (3), it tranformed into (4)

$$\mathbf{X}=\left(\begin{matrix}0&5&0\\0&5&3\\\end{matrix}\right) \tag{4}$$

### Vectorized Method

In [56]:
x = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

Like (3), when we assume $2\times 3$ 2-dimensional matrix $\mathbf{X}$ as (3)

$$\mathbf{X}=\left(\begin{matrix}0&5&-2\\-1&5&3\\\end{matrix}\right)\tag{5}$$

In [57]:
y = np.maximum(x, 0.)
y

array([[0., 5., 0.],
       [0., 5., 3.]])

## Comparing Execution Time: Naive vs. Vectorized Methods

### Matrix Addition

### ReLU

In [58]:
import time
x = np.random.uniform(-10, 10, size=(20, 100))

t0 = time.time()
for _ in range(1000):
    y = naive_relu(x)
print("Naive method took: {0:.2f} s".format(time.time() - t0))

t0 = time.time()
for _ in range(1000):
    y = np.maximum(x, 0.)
print("Vectorized method took: {0:.2f} s".format(time.time() - t0))

Naive method took: 0.85 s
Vectorized method took: 0.00 s


When we see the code above, we can see that naive method need more time for applying ReLU function compared to vectorized method.