## Packages

In [ ]:
import numpy as np
import time
import tensorflow as tf
from tensorflow.keras.datasets import mnist

---

# Vectorized Calculation

## Matrix Addition

### Concept

Let's assume there is $2\times 3$ 2-dimensional matrices $\mathbf{A}, \mathbf{B}$ as

$$\mathbf{A}=\left(\begin{matrix}0&5&-2\\-1&5&3\end{matrix}\right),\ \mathbf{B}=\left(\begin{matrix}5&-3&9\\-2&1&-4\end{matrix}\right) \tag{1}$$

Matrix (1) can be generalized as

$$\mathbf{A}=\left(\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\\end{matrix}\right),\ \mathbf{B}=\left(\begin{matrix}b_{11}&b_{12}&b_{13}\\b_{21}&b_{22}&b_{23}\\\end{matrix}\right)\tag{2}$$

Generalized addition of matrices $\mathbf{A}, \mathbf{B}$ can be denoted by

$$\mathbf{A}+\mathbf{B}=\left(\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\\end{matrix}\right)+\left(\begin{matrix}b_{11}&b_{12}&b_{13}\\b_{21}&b_{22}&b_{23}\\\end{matrix}\right)=\left(\begin{matrix}a_{11}+b_{11}&a_{12}+b_{12}&a_{13}+b_{13}\\a_{21}+b_{21}&a_{22}+b_{22}&a_{23}+b_{23}\\\end{matrix}\right)\tag{3}$$

With (1) and (3), matrix addition of $\mathbf{A}$ and $\mathbf{B}$ can be calculated by

$$\mathbf{A}+\mathbf{B}=\left(\begin{matrix}0&5&-2\\-1&5&3\end{matrix}\right)+\left(\begin{matrix}5&-3&9\\-2&1&-4\end{matrix}\right)=\left(\begin{matrix}5&2&7\\-3&6&-1\end{matrix}\right) \tag{4}$$

### Naive Method

Let's assume there is $2\times 3$ 2-dimensional matrices $\mathbf{A}, \mathbf{B}$ as (1)

In [130]:
a = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

b = np.array([
    [5, -3, 9],
    [-2, 1, -4]
])

We can make algorithm for addition on matrices $\mathbf{A}$ and $\mathbf{B}$ using nested for loop as

<hr style="width: 100%; margin-left: 0; margin-bottom: 0px; border: 0.5px solid black;">
<strong>Algorithm</strong> naive_add(a, b)
<hr style="width: 100%; margin-left: 0; margin-top: 0px; margin-bottom: 0px; border: 0.5px solid black;">
<strong>Input</strong> $m\times n$ 2-dimensional matrices $\mathbf{A}$ and $\mathbf{B}$<br>
&emsp; <strong>Let</strong> $\mathbf{C}$ ← copy of $\mathbf{A}$<br>
&emsp; <strong>for</strong> $i=0$ <strong>to</strong> $m-1$ <strong>do</strong><br>
&emsp;&emsp; <strong>for</strong> $j=0$ <strong>to</strong> $n-1$ <strong>do</strong><br>
&emsp;&emsp;&emsp; $\mathbf{C}[i][j]=\mathbf{C}[i][j]+\mathbf{B}[i][j]$ <br>  
<strong>Output</strong> $m\times n$ 2-dimensional matrix $\mathbf{C}$, sum of $\mathbf{A}$ and $\mathbf{B}$
<hr style="width: 100%; margin-left: 0; margin-top: 0px; border: 0.5px solid black;">

With algorithm, we can apply matirx addition on python as

In [131]:
def naive_add(a, b):
    assert len(a.shape) == 2
    assert a.shape == b.shape
    c = a.copy()
    for i in range(c.shape[0]):
        for j in range(c.shape[1]):
            c[i, j] += b[i, j]
    return c
naive_add(a, b)

array([[ 5,  2,  7],
       [-3,  6, -1]])

### Vectorized Method

In [132]:
a = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

b = np.array([
    [5, -3, 9],
    [-2, 1, -4]
])

In [133]:
c = a + b
c

array([[ 5,  2,  7],
       [-3,  6, -1]])

## Relu

### Concept

![image](img/graph-relu.png)

$$f(y)=max(0, x) \tag{5}$$

(5) can be denoted by

$$f(y)=\begin{cases}0,\ x< 0\\x,\ x\geq 0\end{cases} \tag{6}$$

Let's assume there is $2\times 3$ 2-dimensional matrix $\mathbf{X}$ as

$$\mathbf{X}=\left(\begin{matrix}0&5&-2\\-1&5&3\\\end{matrix}\right)\tag{7}$$

Matrix (7) can be generalized as

$$\mathbf{X}=\left(\begin{matrix}x_{11}&x_{12}&x_{13}\\x_{21}&x_{22}&x_{23}\\\end{matrix}\right)\tag{8}$$

Based on (8), if we apply (6) on (7) element-wise,

<div align="center">

|$x$|Case|$f(x)$|$y$|
|:-:|:-:|:-:|:-:|
|$x_{11}=0$|$0\geq 0$|$y=x$|$x_{11}=0$  |
|$x_{12}=5$|$5\geq 0$|$y=x$|$x_{12}=5$ |
|$x_{13}=-2$|$-2<0$|$y=0$|$x_{13}=0$ |
|$x_{21}=-1$|$-1<0$|$y=0$|$x_{21}=0$ |
|$x_{22}=5$|$5\geq 0$|$y=x$|$x_{22}=5$ |
|$x_{23}=3$|$3\geq 0$|$y=x$|$x_{23}=3$ |

</div>

Therefore, we can get matrix applied ReLU as

$$\mathbf{Y}=\left(\begin{matrix}0&5&0\\0&5&3\\\end{matrix}\right) \tag{8}$$

### Naive Method

Let's assume there is $2\times 3$ 2-dimensional matrix $\mathbf{X}$ as (7)

In [134]:
x = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

We can make algorithm for ReLU on matrix $\mathbf{X}$ using nested for loop as

<hr style="width: 100%; margin-left: 0; margin-bottom: 0px; border: 0.5px solid black;">
<strong>Algorithm</strong> naive_relu(x)
<hr style="width: 100%; margin-left: 0; margin-top: 0px; margin-bottom: 0px; border: 0.5px solid black;">
<strong>Input</strong> $m\times n$ 2-dimensional matrix $\mathbf{X}$<br>
&emsp; <strong>Let</strong> $\mathbf{Y}$ ← copy of $\mathbf{X}$<br>
&emsp; <strong>for</strong> $i=0$ <strong>to</strong> $m-1$ <strong>do</strong><br>
&emsp;&emsp; <strong>for</strong> $j=0$ <strong>to</strong> $n-1$ <strong>do</strong><br>
&emsp;&emsp;&emsp; <strong>if</strong> $\mathbf{Y}[i][j]<0$ <strong>then</strong><br> 
&emsp;&emsp;&emsp;&emsp; $\mathbf{Y}[i][j]$ ← $0$<br>
<strong>Output</strong> $m\times n$ 2-dimensional matrix $\mathbf{Y}$ with ReLU applied
<hr style="width: 100%; margin-left: 0; margin-top: 0px; border: 0.5px solid black;">

With algorithm, we can apply ReLU on python as

In [135]:
def naive_relu(x):
    assert len(x.shape) == 2
    y = x.copy()
    for i in range(y.shape[0]):
        for j in range(y.shape[1]):
            y[i, j] = max(y[i, j], 0)
    return y
naive_relu(x)

array([[0, 5, 0],
       [0, 5, 3]])

### Vectorized Method

Like previous method, assume $2\times 3$ 2-dimensional matrix $\mathbf{X}$ as

In [136]:
x = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

In [137]:
y = np.maximum(x, 0.)
y

array([[0., 5., 0.],
       [0., 5., 3.]])

## Comparing Execution Time: Naive vs. Vectorized Methods

### Matrix Addition

In [138]:
a = np.random.uniform(-10, 10, size=(20, 100))
b = np.random.uniform(-10, 10, size=(20, 100))

t0 = time.time()
for _ in range(1000):
    c = naive_add(a, b)
print("Naive method: {0:.2f} s".format(time.time() - t0))

t0 = time.time()
for _ in range(1000):
    c = a + b
print("Vectorized method: {0:.2f} s".format(time.time() - t0))

Naive method: 0.85 s
Vectorized method: 0.00 s


When we see the code above, we can see that naive method need more time for applying matrix addition compared to vectorized method

### ReLU

In [139]:
x = np.random.uniform(-10, 10, size=(20, 100))

t0 = time.time()
for _ in range(1000):
    y = naive_relu(x)
print("Naive method: {0:.2f} s".format(time.time() - t0))

t0 = time.time()
for _ in range(1000):
    y = np.maximum(x, 0.)
print("Vectorized method: {0:.2f} s".format(time.time() - t0))

Naive method: 0.92 s
Vectorized method: 0.01 s


When we see the code above, we can see that naive method need more time for applying ReLU function compared to vectorized method

### Conclusion

The naive method performs element-wise calculations using a nested for loop, which consumes more computational resources.  
On the other hand, the vectorized method uses optimized operations implemented in low-level languages(Computer science).  
Therefore, the performance of the vectorized method is significantly better than that of the naive method.

---

# Broadcasting

## Concept

Let's assume there are $2\times 3$ 2-dimensional matrix $\mathbf{A}$ and $1\times 3$ row vector $\mathbf{b}$ as

$$\mathbf{A}=\left(\begin{matrix}0&5&-2\\-1&5&3\end{matrix}\right),\ \mathbf{b}=\left(\begin{matrix}5&-3&9\\\end{matrix}\right) \tag{9}$$

We can't conduct matrix addition on matrics with different dimension

$$\mathbf{A}+\mathbf{b}=\left(\begin{matrix}0&5&-2\\-1&5&3\end{matrix}\right)+\left(\begin{matrix}5&-3&9\\\end{matrix}\right)=? \tag{10}$$

Broadcasting fill dimension difference with orignal element of matrix to enable matrix calculation with different dimension  
By (9), we have $1\times3$ row vector $\mathbf{b}$, if we extend $1\times3$ row vector to $2\times3$ matrix, we will be able to calculate (10)

$$\mathbf{b}=\left(\begin{matrix}5&-3&9\\\end{matrix}\right) \tag{11}$$

However, we don't have original value on extended location as

$$\mathbf{b}'=\left(\begin{matrix}5&-3&9\\?&?&?\\\end{matrix}\right) \tag{12}$$

In broadcasting, it uses previous elements for unknown values as

$$\mathbf{b}'=\left(\begin{matrix}5&-3&9\\5&-3&9\end{matrix}\right) \tag{13}$$

With (10), (13) we can get matrix addition with broadcating

$$\mathbf{A}+\mathbf{b}'=\left(\begin{matrix}0&5&-2\\-1&5&3\end{matrix}\right)+\left(\begin{matrix}5&-3&9\\5&-3&9\end{matrix}\right)=\left(\begin{matrix}5&2&7\\4&2&12\end{matrix}\right) \tag{14}$$

When we have generalized form of (11) as

$$\mathbf{b}=\left(\begin{matrix}b_{11}&b_{12}&b_{13}\\\end{matrix}\right) \tag{15}$$

We can horizontly extend (15) using broadcasting as

$$\mathbf{b}'=\left(\begin{matrix}b_{11}&b_{12}&b_{13}\\b_{11}&b_{12}&b_{13}\end{matrix}\right) \tag{16}$$

Also, broadcasting can be used on column vector if we calculate $\mathbf{A}^T+\mathbf{b}$

$$\mathbf{b}=\left(\begin{matrix}b_{11}\\b_{21}\\b_{31}\end{matrix}\right) \tag{17}$$

We can vertically extend (17) using broadcasting as

$$\mathbf{b}'=\left(\begin{matrix}b_{11}&b_{11}\\b_{21}&b_{21}\\b_{31}&b_{31}\end{matrix}\right) \tag{18}$$

Last, broadcasting can be used on scaler like

$$b=b_{11}\tag{19}$$

If we apply broadcasting on (19), if we calculate $\mathbf{A}+b$,

$$b'=\left(\begin{matrix}b_{11}&b_{11}&b_{11}\\b_{11}&b_{11}&b_{11}\end{matrix}\right)\tag{20}$$

To apply broadcasting, at least one of the two elements must be a scalar or have a dimension of size 1 in the mismatched axis. Otherwise, broadcasting cannot be applied.

## Code

Let's assume there are $2\times 3$ 2-dimensional matrix $\mathbf{A}$ and $1\times 3$ row vector $\mathbf{b}$ as (9),

In [140]:
a = np.array([
    [0, 5, -2],
    [-1, 5, 3]
])

b = np.array([
    [5, -3, 9]
])

If we just conduct matrix addition without any transform, NumPy automatically apply broadcasting to matrix

In [141]:
c = a + b
c

array([[ 5,  2,  7],
       [ 4,  2, 12]])

Broadcasting can be applied on scalar very well

In [142]:
b = 1
c = a + b
c

array([[ 1,  6, -1],
       [ 0,  6,  4]])

---

# Reshaping

## Concept

Let's assume there is $3\times 2$ 2-dimensional matrix $\mathbf{X}$ as

$$\mathbf{X}=\left(\begin{matrix}0&1\\2&3\\4&5\\\end{matrix}\right)\tag{21}$$

But for matrix operations, we have to reshape it into a vector. We can change form into $6\times1$ column vector like

$$\mathbf{X}'=\left(\begin{matrix}0\\1\\2\\3\\4\\5\\\end{matrix}\right)\tag{22}$$

To apply reshaping, the total number of elements before and after reshaping must be same.

## Code

Let's assume there is $3\times 2$ 2-dimensional matrix $\mathbf{X}$ as (22)

In [146]:
x = np.array([[0., 1.],
             [2., 3.],
             [4., 5.]])
x.shape

(3, 2)

By .reshape() method, we can change $3\times 2$ 2-dimensional matrix into $6\times1$ column vector

In [148]:
x = x.reshape((6, 1))
x.shape

(6, 1)

We can apply this method on image data too. When we have $60,000$ images with $28\times28$ pixels,

In [143]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
train_images.shape

(60000, 28, 28)

Image data with $28\times28$ pixels, can be denoted as $28\times28$ 2-dimensional matrix, can be transformed into $784\times1$ column vector

In [145]:
train_images = train_images.reshape((60000, 28 * 28))
train_images.shape

(60000, 784)